//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_000703.MD
{
    using System;
    using System.Data.Entity;
    using P_000703.Entidades;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SEGUROSEntities : DbContext
    {
        public SEGUROSEntities()
            : base("name=SEGUROSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<PA_CONS_POL_POLIZA_Result> PA_CONS_POL_POLIZA(ObjectParameter eSTADO, ObjectParameter mENSAJE)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_CONS_POL_POLIZA_Result>("PA_CONS_POL_POLIZA", eSTADO, mENSAJE);
        }
    
        public virtual ObjectResult<PA_CONS_POL_POLIZA_X_CLIENTE_Result> PA_CONS_POL_POLIZA_X_CLIENTE(Nullable<System.Guid> p_crm_cliente, ObjectParameter eSTADO, ObjectParameter mENSAJE)
        {
            var p_crm_clienteParameter = p_crm_cliente.HasValue ?
                new ObjectParameter("p_crm_cliente", p_crm_cliente) :
                new ObjectParameter("p_crm_cliente", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_CONS_POL_POLIZA_X_CLIENTE_Result>("PA_CONS_POL_POLIZA_X_CLIENTE", p_crm_clienteParameter, eSTADO, mENSAJE);
        }
    
        public virtual ObjectResult<PA_CONS_POL_TIPO_CUBRIMIENTO_Result> PA_CONS_POL_TIPO_CUBRIMIENTO(ObjectParameter eSTADO, ObjectParameter mENSAJE)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_CONS_POL_TIPO_CUBRIMIENTO_Result>("PA_CONS_POL_TIPO_CUBRIMIENTO", eSTADO, mENSAJE);
        }
    
        public virtual ObjectResult<PA_CONS_POL_TIPO_RIESGO_Result> PA_CONS_POL_TIPO_RIESGO(ObjectParameter eSTADO, ObjectParameter mENSAJE)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_CONS_POL_TIPO_RIESGO_Result>("PA_CONS_POL_TIPO_RIESGO", eSTADO, mENSAJE);
        }
    
        public virtual int PA_MANT_POL_POLIZA(Nullable<int> p_tipo_operacion, Nullable<System.Guid> p_pol_poliza, string p_nombre, Nullable<System.Guid> p_pol_tipo_cubrimiento, string p_descripcion, Nullable<System.DateTime> p_inicio_vigencia, Nullable<int> p_periodo_cobertura, Nullable<decimal> p_precio, Nullable<System.Guid> p_pol_tipo_riesgo, ObjectParameter eSTADO, ObjectParameter mENSAJE)
        {
            var p_tipo_operacionParameter = p_tipo_operacion.HasValue ?
                new ObjectParameter("p_tipo_operacion", p_tipo_operacion) :
                new ObjectParameter("p_tipo_operacion", typeof(int));
    
            var p_pol_polizaParameter = p_pol_poliza.HasValue ?
                new ObjectParameter("p_pol_poliza", p_pol_poliza) :
                new ObjectParameter("p_pol_poliza", typeof(System.Guid));
    
            var p_nombreParameter = p_nombre != null ?
                new ObjectParameter("p_nombre", p_nombre) :
                new ObjectParameter("p_nombre", typeof(string));
    
            var p_pol_tipo_cubrimientoParameter = p_pol_tipo_cubrimiento.HasValue ?
                new ObjectParameter("p_pol_tipo_cubrimiento", p_pol_tipo_cubrimiento) :
                new ObjectParameter("p_pol_tipo_cubrimiento", typeof(System.Guid));
    
            var p_descripcionParameter = p_descripcion != null ?
                new ObjectParameter("p_descripcion", p_descripcion) :
                new ObjectParameter("p_descripcion", typeof(string));
    
            var p_inicio_vigenciaParameter = p_inicio_vigencia.HasValue ?
                new ObjectParameter("p_inicio_vigencia", p_inicio_vigencia) :
                new ObjectParameter("p_inicio_vigencia", typeof(System.DateTime));
    
            var p_periodo_coberturaParameter = p_periodo_cobertura.HasValue ?
                new ObjectParameter("p_periodo_cobertura", p_periodo_cobertura) :
                new ObjectParameter("p_periodo_cobertura", typeof(int));
    
            var p_precioParameter = p_precio.HasValue ?
                new ObjectParameter("p_precio", p_precio) :
                new ObjectParameter("p_precio", typeof(decimal));
    
            var p_pol_tipo_riesgoParameter = p_pol_tipo_riesgo.HasValue ?
                new ObjectParameter("p_pol_tipo_riesgo", p_pol_tipo_riesgo) :
                new ObjectParameter("p_pol_tipo_riesgo", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_MANT_POL_POLIZA", p_tipo_operacionParameter, p_pol_polizaParameter, p_nombreParameter, p_pol_tipo_cubrimientoParameter, p_descripcionParameter, p_inicio_vigenciaParameter, p_periodo_coberturaParameter, p_precioParameter, p_pol_tipo_riesgoParameter, eSTADO, mENSAJE);
        }
    
        public virtual int PA_MANT_POL_POLIZA_X_CLIENTE(Nullable<int> p_tipo_operacion, Nullable<System.Guid> p_pol_poliza, Nullable<System.Guid> p_crm_cliente, Nullable<System.Guid> p_registrado_por, Nullable<System.DateTime> p_fecha_registro, ObjectParameter eSTADO, ObjectParameter mENSAJE)
        {
            var p_tipo_operacionParameter = p_tipo_operacion.HasValue ?
                new ObjectParameter("p_tipo_operacion", p_tipo_operacion) :
                new ObjectParameter("p_tipo_operacion", typeof(int));
    
            var p_pol_polizaParameter = p_pol_poliza.HasValue ?
                new ObjectParameter("p_pol_poliza", p_pol_poliza) :
                new ObjectParameter("p_pol_poliza", typeof(System.Guid));
    
            var p_crm_clienteParameter = p_crm_cliente.HasValue ?
                new ObjectParameter("p_crm_cliente", p_crm_cliente) :
                new ObjectParameter("p_crm_cliente", typeof(System.Guid));
    
            var p_registrado_porParameter = p_registrado_por.HasValue ?
                new ObjectParameter("p_registrado_por", p_registrado_por) :
                new ObjectParameter("p_registrado_por", typeof(System.Guid));
    
            var p_fecha_registroParameter = p_fecha_registro.HasValue ?
                new ObjectParameter("p_fecha_registro", p_fecha_registro) :
                new ObjectParameter("p_fecha_registro", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_MANT_POL_POLIZA_X_CLIENTE", p_tipo_operacionParameter, p_pol_polizaParameter, p_crm_clienteParameter, p_registrado_porParameter, p_fecha_registroParameter, eSTADO, mENSAJE);
        }
    }
}
